name: Discord Webhook

on:
  push:
    branches:
      - atpbranch

jobs:
  send_discord_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send message to Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}  # Usando o webhook configurado nos secrets
          template: "basic"
          include-extras: true