name: Discord Webhook

on:
  push:
    branches:
      - main  # Ou qualquer outra branch que você deseja monitorar

jobs:
  send_discord_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send message to Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}  
          template: "avatar-with-link"
          include-extras: true