name: Docker CD

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t eubeatrizam/atp:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push eubeatrizam/atp:latest

    - name: Send simple message to Discord
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"content": "Novo código foi enviado para a branch main! 🚀"}' \
        ${{ secrets.DISCORD_WEBHOOK }}
  