name: Python Unit Tests

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Instalar dependências (se houver)
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt  

    - name: Executar testes
      run: |
        python -m unittest discover -s . -p "test.py"